export const IPC = {
  SELECT_FOLDER: 'dialog:selectFolder',
  ANALYZE: 'import:analyze',
  ANALYZE_PROGRESS: 'import:analyze:progress',
  ANALYZE_CANCEL: 'import:analyze:cancel',
  RECOMPUTE_CLUSTERS: 'cluster:recompute',
  GET_THUMBNAIL: 'thumbnail:get',
  GET_LIGHTBOX_PREVIEW: 'thumbnail:getLightboxPreview',
  COPY_START: 'copy:start',
  COPY_PROGRESS: 'copy:progress',
  OPEN_PATH: 'shell:openPath',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  DRIVE_STATUS: 'drive:status',
  DRIVE_CONNECT: 'drive:connect',
  DRIVE_DISCONNECT: 'drive:disconnect',
  DRIVE_UPLOAD_START: 'drive:upload:start',
  DRIVE_UPLOAD_PROGRESS: 'drive:upload:progress',
  DRIVE_OPEN_ROOT: 'drive:openRoot',
  DRIVE_SHARE_GROUP: 'drive:shareGroup'
} as const
